trigger: none
pr: none

parameters:
  - name: testCases
    displayName: "Comma-separated list of testCaseNos"
    type: string
    default: ""

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: ./gradlew cucumber
    displayName: 'Run Cucumber Tests'
    # Optionally pass testCases as property/environment variable

  # Publish Allure Report to Azure DevOps UI
  - task: AllureReport@1
    displayName: 'Publish Allure Report'
    inputs:
      reportDir: 'build/reports/allure-report'

  # (Optional) Also publish as artifact for download
  - task: PublishBuildArtifacts@1
    displayName: 'Upload Allure report'
    inputs:
      PathtoPublish: 'build/reports/allure-report'
      ArtifactName: 'allure-report'
      publishLocation: 'Container'
