trigger: none

pr: none

# This pipeline is intended to be run manually with parameters, similar to workflow_dispatch in GitHub Actions.
# To run: Click "Run pipeline" in Azure DevOps UI.

parameters:
  - name: testCases
    displayName: "Comma-separated list of testCaseNos"
    type: string
    default: ""

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: ./gradlew cucumber
    displayName: 'Run Cucumber Tests'
    # If testCases needs to be passed as an environment variable or gradle property, adjust accordingly:
    # env:
    #   TEST_CASES: ${{ parameters.testCases }}
    # Or use: ./gradlew cucumber -PtestCases=${{ parameters.testCases }}

  - task: PublishBuildArtifacts@1
    displayName: 'Upload Allure report'
    inputs:
      PathtoPublish: 'build/reports/allure-report'
      ArtifactName: 'allure-report'
      publishLocation: 'Container'