name: Run Cucumber Tests

on:
  workflow_dispatch:
    inputs:
      testCases:
        description: "Comma-separated list of testCaseNos"
        required: false
        default: ""
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: ./gradlew cucumber
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report
